spring:
  application:
    name: personal-newsletter-api
    
  redis:
    host: localhost
    port: 6379
    ssl: false
    password:  # 비밀번호가 없는 경우 빈 값으로 둘 수 있습니다

  profiles:
    active: local

  port: 8080
